import { Inter } from "next/font/google";
import { Poppins } from "next/font/google";
import { Great_Vibes } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({ subsets: ["latin"], weight:'400' });
const great_vibes = Great_Vibes({subsets: ['latin'], weight: '400'})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={great_vibes.className}>{children}</body>
    </html>
  );
}
